
from pandas import read_excel
from warnings import filterwarnings

filterwarnings('ignore', category = UserWarning, module = 'openpyxl')

data = read_excel("metadata/Channelrhodopsins_Updated_List.xlsx", sheet_name = "full_channelrhodopsins")

all_sequences = {}
fun_sequences = {}

for i, row in data.iterrows():
    name = row['Sequence name']
    seq = row['Rhodopsin domain sequence'].upper()
    all_sequences[name] = seq
    if row['Currents'] and row['Currents'] == row['Currents'] and row['Currents'] != 'no photocurrents':
        fun_sequences[name] = seq

rule all:
    input:
        expand("analysis/all/iqtree.treefile.midpoint", set = [ 'all', 'fun' ])

rule write_fasta:
    output:
        "analysis/{set}/sequences.fasta"
    params:
        seq = lambda w: fun_sequences if w.set == 'fun' else all_sequences
    script:
        "scripts/write_fasta.py"

rule mafft:
    input:
        "analysis/{set}/cdhit.fasta"
    output:
        "analysis/{set}/mafft.fasta"
    conda:
        "envs/tools.yaml"
    threads:
        workflow.cores
    shell:
        "mafft --thread {threads} --auto {input} > {output}"

rule cdhit:
    input:
        "analysis/{set}/sequences.fasta"
    output:
        "analysis/{set}/cdhit.fasta"
    params:
        c = 1
    conda:
        "envs/tools.yaml"
    shell:
        "cdhit -i {input} -o {output} -c {params.c} -d 0"

rule trimal:
    input:
        "analysis/{set}/mafft.fasta"
    output:
        "analysis/{set}/trimal.fasta"
    params:
        gt = 0.1
    conda:
        "envs/tools.yaml"
    shell:
        "trimal -in {input} -out {output} -gt {params.gt}"

rule midpoint:
    input:
        "analysis/{set}/iqtree.treefile"
    output:
        "analysis/{set}/iqtree.treefile.midpoint"
    conda:
        "envs/gotree.yaml"
    shell:
        "gotree reroot midpoint -i {input} -o {output}"

rule iqtree_protein:
    input:
        "analysis/{set}/trimal.fasta"
    output:
        "analysis/{set}/iqtree.treefile"
    params:
        seed = 123,
        B = 1000,
        prefix = "analysis/{set}/iqtree"
    threads:
        4
    conda:
        "envs/tools.yaml"
    shell:
        "iqtree2 -seed {params.seed} -s {input} -B {params.B} -T {threads} --prefix {params.prefix} -redo"
